"""
Classification rules: Necessary vs Unnecessary (with reason).

Rules are path/pattern based and intentionally conservative so important
user and system data is never marked safe-to-delete by default.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import Optional

from .models import Classification


@dataclass(frozen=True)
class RuleMatch:
    classification: Classification
    reason: str
    category: str
    safe_to_delete: bool
    # If True, treat as a known target folder (scan its children for size)
    is_target_root: bool = False


# Exact / prefix path patterns relative to drive root (normalized lowercase, with \)
# Order matters: first match wins.

_UNNECESSARY_TARGETS: list[tuple[str, str, str, bool]] = [
    # (relative path prefix or marker, category, reason, safe_to_delete)
    (
        r"$recycle.bin",
        "Recycle Bin",
        "Items already deleted by the user; emptying frees space. Contents are not restored after clean.",
        True,
    ),
    (
        r"windows\temp",
        "Windows Temp",
        "Windows temporary files that are safe to remove when no installers are running.",
        True,
    ),
    (
        r"windows\softwaredistribution\download",
        "Windows Update Cache",
        "Downloaded Windows Update packages already applied; Windows will re-download if needed.",
        True,
    ),
    (
        r"windows\prefetch",
        "Prefetch",
        "Windows Prefetch cache used to speed app startup; Windows rebuilds it automatically.",
        True,
    ),
    (
        r"windows\logs",
        "Windows Logs",
        "System and setup log files; useful for troubleshooting but not required for daily use.",
        True,
    ),
    (
        r"windows\minidump",
        "Crash Dumps",
        "Blue-screen / crash dump files kept for debugging; safe to remove if issues are resolved.",
        True,
    ),
    (
        r"temp",
        "Drive Temp",
        "Root-level Temp folder used by installers and apps; safe when no installs are in progress.",
        True,
    ),
]

# User-profile relative targets (under Users\<name>\...)
_USER_UNNECESSARY: list[tuple[str, str, str, bool]] = [
    (
        r"appdata\local\temp",
        "User Temp",
        "Per-user temporary files (%TEMP%). Applications recreate them as needed.",
        True,
    ),
    (
        r"appdata\local\microsoft\windows\inetcache",
        "Browser / IE Cache",
        "Cached internet files; browsers will re-download content when visited again.",
        True,
    ),
    (
        r"appdata\local\microsoft\windows\webcache",
        "Web Cache",
        "Local web cache database; regenerated by the system.",
        True,
    ),
    (
        r"appdata\local\microsoft\windows\explorer\thumbcache_",
        "Thumbnail Cache",
        "Explorer thumbnail cache; rebuilt when folders are browsed.",
        True,
    ),
    (
        r"appdata\local\crashdumps",
        "App Crash Dumps",
        "Application crash dump files for debugging; removable if apps are stable.",
        True,
    ),
    (
        r"appdata\local\pip\cache",
        "Python pip Cache",
        "Cached Python packages from pip; can be re-downloaded.",
        True,
    ),
    (
        r"appdata\local\npm-cache",
        "npm Cache",
        "Node.js npm package cache; can be re-downloaded.",
        True,
    ),
    (
        r"appdata\roaming\microsoft\windows\recent",
        "Recent Items",
        "Shortcuts to recently opened files (not the files themselves).",
        True,
    ),
]

_NECESSARY_PREFIXES: list[tuple[str, str, str]] = [
    (
        r"windows\system32",
        "System Critical",
        "Core Windows system binaries and libraries. Removing these can break Windows.",
    ),
    (
        r"windows\syswow64",
        "System Critical",
        "32-bit Windows system files on 64-bit Windows. Required for compatibility.",
    ),
    (
        r"windows\winsxs",
        "System Critical",
        "Windows component store. Required for updates and features.",
    ),
    (
        r"windows\boot",
        "System Critical",
        "Boot configuration and files required to start Windows.",
    ),
    (
        r"program files",
        "Installed Programs",
        "Installed application files. Removing them breaks installed software.",
    ),
    (
        r"program files (x86)",
        "Installed Programs",
        "32-bit installed application files. Required for those programs to run.",
    ),
    (
        r"programdata",
        "Program Data",
        "Shared application and system configuration data.",
    ),
    (
        r"users\public",
        "Shared User Data",
        "Shared public user documents and media.",
    ),
    (
        r"recovery",
        "Recovery",
        "Windows recovery environment data used for repair and reset.",
    ),
    (
        r"system volume information",
        "System Protection",
        "System Restore and volume shadow copy metadata. Do not delete manually.",
    ),
    (
        r"$windows.~bt",
        "Windows Upgrade",
        "Windows upgrade staging folder. Managed by Windows Update / Setup.",
    ),
    (
        r"$windows.~ws",
        "Windows Upgrade",
        "Windows upgrade working files. Managed by Windows Setup.",
    ),
]

_USER_NECESSARY_SUFFIXES: list[tuple[str, str, str]] = [
    (r"documents", "User Documents", "Personal documents. Treat as important user data."),
    (r"desktop", "User Desktop", "Files on the desktop. Treat as important user data."),
    (r"pictures", "User Pictures", "Personal photos and images."),
    (r"videos", "User Videos", "Personal video files."),
    (r"music", "User Music", "Personal music files."),
    (r"downloads", "User Downloads", "Downloaded files. Review before deleting — may include important installers or documents."),
    (r"onedrive", "OneDrive", "Cloud-synced personal files."),
    (r"favorites", "Favorites", "Browser favorites / bookmarks shortcuts."),
    (r"contacts", "Contacts", "User contact data."),
]

# Root files that must never be cleaned
_NECESSARY_ROOT_FILES = {
    "pagefile.sys": ("Virtual Memory", "Windows page file used as virtual memory. Required for system stability."),
    "hiberfil.sys": ("Hibernation", "Hibernation file. Required if hibernate/fast startup is enabled."),
    "swapfile.sys": ("Virtual Memory", "Windows swap file used by the system."),
    "bootmgr": ("Boot", "Windows boot manager. Required to start the OS."),
}


def _norm(path: str) -> str:
    return os.path.normpath(path).replace("/", "\\").lower().rstrip("\\")


def _drive_root(path: str) -> str:
    drive, _ = os.path.splitdrive(os.path.abspath(path))
    return (drive + "\\").lower()


def _rel_to_drive(path: str) -> str:
    full = _norm(path)
    root = _drive_root(path)
    if full.startswith(root.rstrip("\\")):
        rel = full[len(root) :]
        return rel.lstrip("\\")
    return full


def classify_path(path: str, is_directory: bool = False) -> Optional[RuleMatch]:
    """
    Classify a path. Returns None if no specific rule applies
    (caller may skip or mark as Review for large unknown items).
    """
    full = _norm(path)
    rel = _rel_to_drive(path)
    name = os.path.basename(full)

    # Root-level protected files
    if name in _NECESSARY_ROOT_FILES and "\\" not in rel:
        cat, reason = _NECESSARY_ROOT_FILES[name]
        return RuleMatch(Classification.NECESSARY, reason, cat, False)

    # Necessary prefixes
    for prefix, category, reason in _NECESSARY_PREFIXES:
        if rel == prefix or rel.startswith(prefix + "\\"):
            # Exception: allow known unnecessary subpaths under Windows
            override = _check_unnecessary(rel)
            if override:
                return override
            return RuleMatch(Classification.NECESSARY, reason, category, False)

    # Unnecessary targets
    unn = _check_unnecessary(rel)
    if unn:
        return unn

    # Users\<name>\...
    m = re.match(r"^users\\[^\\]+\\(.+)$", rel)
    if m:
        user_rel = m.group(1)
        for prefix, category, reason, safe in _USER_UNNECESSARY:
            if prefix.endswith("thumbcache_"):
                # Match thumbcache_*.db files under Explorer
                base = prefix[: -len("thumbcache_")]
                name = user_rel.rsplit("\\", 1)[-1]
                if user_rel.startswith(base) and name.startswith("thumbcache_"):
                    return RuleMatch(Classification.UNNECESSARY, reason, category, safe, True)
            elif user_rel == prefix or user_rel.startswith(prefix + "\\"):
                return RuleMatch(Classification.UNNECESSARY, reason, category, safe, True)

        for suffix, category, reason in _USER_NECESSARY_SUFFIXES:
            # match folder name at this level or deeper known profile folders
            parts = user_rel.split("\\")
            if parts and parts[0] == suffix:
                # Downloads → Review (not auto-clean)
                if suffix == "downloads":
                    return RuleMatch(Classification.REVIEW, reason, category, False, True)
                return RuleMatch(Classification.NECESSARY, reason, category, False, True)

        if user_rel.startswith("appdata\\"):
            return RuleMatch(
                Classification.REVIEW,
                "Application data may contain settings, licenses, or caches. Review before removing.",
                "AppData",
                False,
                True,
            )

    # Top-level Users folder itself
    if rel == "users" or re.match(r"^users\\[^\\]+$", rel):
        return RuleMatch(
            Classification.NECESSARY,
            "User profile root. Contains personal and application data.",
            "User Profiles",
            False,
            True,
        )

    # Top-level Windows folder (already partially covered)
    if rel == "windows":
        return RuleMatch(
            Classification.NECESSARY,
            "Windows operating system folder. Do not remove.",
            "System Critical",
            False,
            True,
        )

    return None


def _check_unnecessary(rel: str) -> Optional[RuleMatch]:
    for prefix, category, reason, safe in _UNNECESSARY_TARGETS:
        if rel == prefix or rel.startswith(prefix + "\\"):
            return RuleMatch(Classification.UNNECESSARY, reason, category, safe, True)
    return None


def is_protected_path(path: str) -> bool:
    """Hard block list for cleaner — never delete these."""
    match = classify_path(path)
    if match and match.classification == Classification.NECESSARY:
        return True
    rel = _rel_to_drive(path)
    name = os.path.basename(_norm(path))
    if name in _NECESSARY_ROOT_FILES and "\\" not in rel:
        return True
    critical = (
        r"windows\system32",
        r"windows\syswow64",
        r"windows\winsxs",
        r"windows\boot",
        r"system volume information",
        r"recovery",
        r"program files",
        r"program files (x86)",
    )
    for c in critical:
        if rel == c or rel.startswith(c + "\\"):
            return True
    return False
